const UserSuccess = {
  LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
  USER_REGISTERED_SUCCESSFULLY: 'USER_REGISTERED_SUCCESSFULLY',
}

const TaskSuccess = {
  TASKS_FETCHED_SUCCESSFULLY: 'TASKS_FETCHED_SUCCESSFULLY',
  TASK_CREATED_SUCCESSFULLY: 'TASK_CREATED_SUCCESSFULLY',
  TASK_ENDED_SUCCESSFULLY: 'TASK_ENDED_SUCCESSFULLY',
  TASK_DELETED_SUCCESSFULLY: 'TASK_DELETED_SUCCESSFULLY',
  RUNNING_TASK_FOUND: 'RUNNING_TASK_FOUND',
  NO_RUNNING_TASK: 'NO_RUNNING_TASK',
}

module.exports = {
  UserSuccess,
  TaskSuccess,
}
